{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "comments: true\n",
    "layout: post\n",
    "title: Calculator IPYNB\n",
    "description: Grab Calculator Code and place in IPYNB\n",
    "type: hacks\n",
    "courses: { compsci: {week: 2} }\n",
    "---"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Make a GitHub Pages Repository\n",
    "Understanding Calculator code is a great way to learn JavaScript.\n",
    "- Calculator was obtained from Teacher in _post directory\n",
    "- Calculator also requires assets directory also obtained from Teacher\n",
    "    - assets/css contains customized style for buttons\n",
    "    - assets/js contains vanta animations \n",
    "- Code cell requires `%%html` at the top of cell to support css, html, script."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "vscode": {
     "languageId": "html"
    }
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>\n",
       "  .calculator-output {\n",
       "    /* calulator output \n",
       "      top bar shows the results of the calculator;\n",
       "      result to take up the entirety of the first row;\n",
       "      span defines 4 columns and 1 row\n",
       "    */\n",
       "    grid-column: span 4;\n",
       "    grid-row: span 1;\n",
       "  \n",
       "    padding: 0.25em;\n",
       "    font-size: 20px;\n",
       "    border: 5px solid black;\n",
       "  \n",
       "    display: flex;\n",
       "    align-items: center;\n",
       "  }\n",
       "</style>\n",
       "\n",
       "<!-- Add a container for the animation -->\n",
       "<div id=\"animation\">\n",
       "  <div class=\"calculator-container\">\n",
       "      <!--result-->\n",
       "      <div class=\"calculator-output\" id=\"output\">0</div>\n",
       "      <!--row 1-->\n",
       "      <div class=\"calculator-number\">1</div>\n",
       "      <div class=\"calculator-number\">2</div>\n",
       "      <div class=\"calculator-number\">3</div>\n",
       "      <div class=\"calculator-operation\">+</div>\n",
       "      <!--row 2-->\n",
       "      <div class=\"calculator-number\">4</div>\n",
       "      <div class=\"calculator-number\">5</div>\n",
       "      <div class=\"calculator-number\">6</div>\n",
       "      <div class=\"calculator-operation\">-</div>\n",
       "      <!--row 3-->\n",
       "      <div class=\"calculator-number\">7</div>\n",
       "      <div class=\"calculator-number\">8</div>\n",
       "      <div class=\"calculator-number\">9</div>\n",
       "      <div class=\"calculator-operation\">*</div>\n",
       "      <!--row 4-->\n",
       "      <div class=\"calculator-clear\">A/C</div>\n",
       "      <div class=\"calculator-number\">0</div>\n",
       "      <div class=\"calculator-number\">.</div>\n",
       "      <div class=\"calculator-equals\">=</div>\n",
       "  </div>\n",
       "</div>\n",
       "\n",
       "<!-- JavaScript (JS) implementation of the calculator. -->\n",
       "<script>\n",
       "  // initialize important variables to manage calculations\n",
       "  var firstNumber = null;\n",
       "  var operator = null;\n",
       "  var nextReady = true;\n",
       "  // build objects containing key elements\n",
       "  const output = document.getElementById(\"output\");\n",
       "  const numbers = document.querySelectorAll(\".calculator-number\");\n",
       "  const operations = document.querySelectorAll(\".calculator-operation\");\n",
       "  const clear = document.querySelectorAll(\".calculator-clear\");\n",
       "  const equals = document.querySelectorAll(\".calculator-equals\");\n",
       "\n",
       "  // Number buttons listener\n",
       "  numbers.forEach(button => {\n",
       "    button.addEventListener(\"click\", function() {\n",
       "      number(button.textContent);\n",
       "    });\n",
       "  });\n",
       "\n",
       "  // Number action\n",
       "  function number (value) { // function to input numbers into the calculator\n",
       "      if (value != \".\") {\n",
       "          if (nextReady == true) { // nextReady is used to tell the computer when the user is going to input a completely new number\n",
       "              output.innerHTML = value;\n",
       "              if (value != \"0\") { // if statement to ensure that there are no multiple leading zeroes\n",
       "                  nextReady = false;\n",
       "              }\n",
       "          } else {\n",
       "              output.innerHTML = output.innerHTML + value; // concatenation is used to add the numbers to the end of the input\n",
       "          }\n",
       "      } else { // special case for adding a decimal; can't have two decimals\n",
       "          if (output.innerHTML.indexOf(\".\") == -1) {\n",
       "              output.innerHTML = output.innerHTML + value;\n",
       "              nextReady = false;\n",
       "          }\n",
       "      }\n",
       "  }\n",
       "\n",
       "  // Operation buttons listener\n",
       "  operations.forEach(button => {\n",
       "    button.addEventListener(\"click\", function() {\n",
       "      operation(button.textContent);\n",
       "    });\n",
       "  });\n",
       "\n",
       "  // Operator action\n",
       "  function operation (choice) { // function to input operations into the calculator\n",
       "      if (firstNumber == null) { // once the operation is chosen, the displayed number is stored into the variable firstNumber\n",
       "          firstNumber = parseInt(output.innerHTML);\n",
       "          nextReady = true;\n",
       "          operator = choice;\n",
       "          return; // exits function\n",
       "      }\n",
       "      // occurs if there is already a number stored in the calculator\n",
       "      firstNumber = calculate(firstNumber, parseFloat(output.innerHTML)); \n",
       "      operator = choice;\n",
       "      output.innerHTML = firstNumber.toString();\n",
       "      nextReady = true;\n",
       "  }\n",
       "\n",
       "  // Calculator\n",
       "  function calculate (first, second) { // function to calculate the result of the equation\n",
       "      let result = 0;\n",
       "      switch (operator) {\n",
       "          case \"+\":\n",
       "              result = first + second;\n",
       "              break;\n",
       "          case \"-\":\n",
       "              result = first - second;\n",
       "              break;\n",
       "          case \"*\":\n",
       "              result = first * second;\n",
       "              break;\n",
       "          case \"/\":\n",
       "              result = first / second;\n",
       "              break;\n",
       "          default: \n",
       "              break;\n",
       "      }\n",
       "      return result;\n",
       "  }\n",
       "\n",
       "  // Equals button listener\n",
       "  equals.forEach(button => {\n",
       "    button.addEventListener(\"click\", function() {\n",
       "      equal();\n",
       "    });\n",
       "  });\n",
       "\n",
       "  // Equal action\n",
       "  function equal () { // function used when the equals button is clicked; calculates equation and displays it\n",
       "      firstNumber = calculate(firstNumber, parseFloat(output.innerHTML));\n",
       "      output.innerHTML = firstNumber.toString();\n",
       "      nextReady = true;\n",
       "  }\n",
       "\n",
       "  // Clear button listener\n",
       "  clear.forEach(button => {\n",
       "    button.addEventListener(\"click\", function() {\n",
       "      clearCalc();\n",
       "    });\n",
       "  });\n",
       "\n",
       "  // A/C action\n",
       "  function clearCalc () { // clears calculator\n",
       "      firstNumber = null;\n",
       "      output.innerHTML = \"0\";\n",
       "      nextReady = true;\n",
       "  }\n",
       "</script>\n",
       "\n",
       "<!-- \n",
       "Vanta animations just for fun, load JS onto the page\n",
       "-->\n",
       "<script src=\"/student/assets/js/three.r119.min.js\"></script>\n",
       "<script src=\"/student/assets/js/vanta.halo.min.js\"></script>\n",
       "<script src=\"/student/assets/js/vanta.birds.min.js\"></script>\n",
       "<script src=\"/student/assets/js/vanta.net.min.js\"></script>\n",
       "<script src=\"/student/assets/js/vanta.rings.min.js\"></script>\n",
       "\n",
       "<script>\n",
       "// setup vanta scripts as functions\n",
       "var vantaInstances = {\n",
       "  halo: VANTA.HALO,\n",
       "  birds: VANTA.BIRDS,\n",
       "  net: VANTA.NET,\n",
       "  rings: VANTA.RINGS\n",
       "};\n",
       "\n",
       "// obtain a random vanta function\n",
       "var vantaInstance = vantaInstances[Object.keys(vantaInstances)[Math.floor(Math.random() * Object.keys(vantaInstances).length)]];\n",
       "\n",
       "// run the animation\n",
       "vantaInstance({\n",
       "  el: \"#animation\",\n",
       "  mouseControls: true,\n",
       "  touchControls: true,\n",
       "  gyroControls: false\n",
       "});\n",
       "</script>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%%html\n",
    "<style>\n",
    "  .calculator-output {\n",
    "    /* calulator output \n",
    "      top bar shows the results of the calculator;\n",
    "      result to take up the entirety of the first row;\n",
    "      span defines 4 columns and 1 row\n",
    "    */\n",
    "    grid-column: span 4;\n",
    "    grid-row: span 1;\n",
    "  \n",
    "    padding: 0.25em;\n",
    "    font-size: 20px;\n",
    "    border: 5px solid black;\n",
    "  \n",
    "    display: flex;\n",
    "    align-items: center;\n",
    "  }\n",
    "</style>\n",
    "\n",
    "<!-- Add a container for the animation -->\n",
    "<div id=\"animation\">\n",
    "  <div class=\"calculator-container\">\n",
    "      <!--result-->\n",
    "      <div class=\"calculator-output\" id=\"output\">0</div>\n",
    "      <!--row 1-->\n",
    "      <div class=\"calculator-number\">1</div>\n",
    "      <div class=\"calculator-number\">2</div>\n",
    "      <div class=\"calculator-number\">3</div>\n",
    "      <div class=\"calculator-operation\">+</div>\n",
    "      <!--row 2-->\n",
    "      <div class=\"calculator-number\">4</div>\n",
    "      <div class=\"calculator-number\">5</div>\n",
    "      <div class=\"calculator-number\">6</div>\n",
    "      <div class=\"calculator-operation\">-</div>\n",
    "      <!--row 3-->\n",
    "      <div class=\"calculator-number\">7</div>\n",
    "      <div class=\"calculator-number\">8</div>\n",
    "      <div class=\"calculator-number\">9</div>\n",
    "      <div class=\"calculator-operation\">*</div>\n",
    "      <!--row 4-->\n",
    "      <div class=\"calculator-clear\">A/C</div>\n",
    "      <div class=\"calculator-number\">0</div>\n",
    "      <div class=\"calculator-number\">.</div>\n",
    "      <div class=\"calculator-equals\">=</div>\n",
    "  </div>\n",
    "</div>\n",
    "\n",
    "<!-- JavaScript (JS) implementation of the calculator. -->\n",
    "<script>\n",
    "  // initialize important variables to manage calculations\n",
    "  var firstNumber = null;\n",
    "  var operator = null;\n",
    "  var nextReady = true;\n",
    "  // build objects containing key elements\n",
    "  const output = document.getElementById(\"output\");\n",
    "  const numbers = document.querySelectorAll(\".calculator-number\");\n",
    "  const operations = document.querySelectorAll(\".calculator-operation\");\n",
    "  const clear = document.querySelectorAll(\".calculator-clear\");\n",
    "  const equals = document.querySelectorAll(\".calculator-equals\");\n",
    "\n",
    "  // Number buttons listener\n",
    "  numbers.forEach(button => {\n",
    "    button.addEventListener(\"click\", function() {\n",
    "      number(button.textContent);\n",
    "    });\n",
    "  });\n",
    "\n",
    "  // Number action\n",
    "  function number (value) { // function to input numbers into the calculator\n",
    "      if (value != \".\") {\n",
    "          if (nextReady == true) { // nextReady is used to tell the computer when the user is going to input a completely new number\n",
    "              output.innerHTML = value;\n",
    "              if (value != \"0\") { // if statement to ensure that there are no multiple leading zeroes\n",
    "                  nextReady = false;\n",
    "              }\n",
    "          } else {\n",
    "              output.innerHTML = output.innerHTML + value; // concatenation is used to add the numbers to the end of the input\n",
    "          }\n",
    "      } else { // special case for adding a decimal; can not have two decimals\n",
    "          if (output.innerHTML.indexOf(\".\") == -1) {\n",
    "              output.innerHTML = output.innerHTML + value;\n",
    "              nextReady = false;\n",
    "          }\n",
    "      }\n",
    "  }\n",
    "\n",
    "  // Operation buttons listener\n",
    "  operations.forEach(button => {\n",
    "    button.addEventListener(\"click\", function() {\n",
    "      operation(button.textContent);\n",
    "    });\n",
    "  });\n",
    "\n",
    "  // Operator action\n",
    "  function operation (choice) { // function to input operations into the calculator\n",
    "      if (firstNumber == null) { // once the operation is chosen, the displayed number is stored into the variable firstNumber\n",
    "          firstNumber = parseInt(output.innerHTML);\n",
    "          nextReady = true;\n",
    "          operator = choice;\n",
    "          return; // exits function\n",
    "      }\n",
    "      // occurs if there is already a number stored in the calculator\n",
    "      firstNumber = calculate(firstNumber, parseFloat(output.innerHTML)); \n",
    "      operator = choice;\n",
    "      output.innerHTML = firstNumber.toString();\n",
    "      nextReady = true;\n",
    "  }\n",
    "\n",
    "  // Calculator\n",
    "  function calculate (first, second) { // function to calculate the result of the equation\n",
    "      let result = 0;\n",
    "      switch (operator) {\n",
    "          case \"+\":\n",
    "              result = first + second;\n",
    "              break;\n",
    "          case \"-\":\n",
    "              result = first - second;\n",
    "              break;\n",
    "          case \"*\":\n",
    "              result = first * second;\n",
    "              break;\n",
    "          case \"/\":\n",
    "              result = first / second;\n",
    "              break;\n",
    "          default: \n",
    "              break;\n",
    "      }\n",
    "      return result;\n",
    "  }\n",
    "\n",
    "  // Equals button listener\n",
    "  equals.forEach(button => {\n",
    "    button.addEventListener(\"click\", function() {\n",
    "      equal();\n",
    "    });\n",
    "  });\n",
    "\n",
    "  // Equal action\n",
    "  function equal () { // function used when the equals button is clicked; calculates equation and displays it\n",
    "      firstNumber = calculate(firstNumber, parseFloat(output.innerHTML));\n",
    "      output.innerHTML = firstNumber.toString();\n",
    "      nextReady = true;\n",
    "  }\n",
    "\n",
    "  // Clear button listener\n",
    "  clear.forEach(button => {\n",
    "    button.addEventListener(\"click\", function() {\n",
    "      clearCalc();\n",
    "    });\n",
    "  });\n",
    "\n",
    "  // A/C action\n",
    "  function clearCalc () { // clears calculator\n",
    "      firstNumber = null;\n",
    "      output.innerHTML = \"0\";\n",
    "      nextReady = true;\n",
    "  }\n",
    "</script>\n",
    "\n",
    "<!-- \n",
    "Vanta animations just for fun, load JS onto the page\n",
    "-->\n",
    "<script src=\"/student/assets/js/three.r119.min.js\"></script>\n",
    "<script src=\"/student/assets/js/vanta.halo.min.js\"></script>\n",
    "<script src=\"/student/assets/js/vanta.birds.min.js\"></script>\n",
    "<script src=\"/student/assets/js/vanta.net.min.js\"></script>\n",
    "<script src=\"/student/assets/js/vanta.rings.min.js\"></script>\n",
    "\n",
    "<script>\n",
    "// setup vanta scripts as functions\n",
    "var vantaInstances = {\n",
    "  halo: VANTA.HALO,\n",
    "  birds: VANTA.BIRDS,\n",
    "  net: VANTA.NET,\n",
    "  rings: VANTA.RINGS\n",
    "};\n",
    "\n",
    "// obtain a random vanta function\n",
    "var vantaInstance = vantaInstances[Object.keys(vantaInstances)[Math.floor(Math.random() * Object.keys(vantaInstances).length)]];\n",
    "\n",
    "// run the animation\n",
    "vantaInstance({\n",
    "  el: \"#animation\",\n",
    "  mouseControls: true,\n",
    "  touchControls: true,\n",
    "  gyroControls: false\n",
    "});\n",
    "</script>"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
